# Generated by Django 5.1.8 on 2025-04-16 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(default="datetime.datetime.now().strftime('%Y-%m-%d_%H-%M-%S')[:10]", max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
            preserve_default=False,
        ),
    ]
